workflows:
  app_preview:
    name: app_preview
    max_build_duration: 120
    instance_type: mac_mini_m2
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      scripts:
        - name: Post App Preview
          script: |
            dart pub global activate codemagic_app_preview
            app_preview post \
             --github_token $GITHUB_PAT \
             --codemagic_token $CODEMAGIC_TOKEN
